### PR TITLE
Fixed dependency issues for Kibana v7.0.x

### PR DESCRIPTION
**Pull request by andresbrandworkz**
Modified some dependencies to make it work with Kibana v7.0.x

### CODE REVIEW

**Comment by nreese** [comment]
Thanks for getting the plugin working in 7.0. Appreciate the help.

**Comment by SiwyDym** [comment]
There is no typo in import in `time.less`?
is
`@import (reference) "../../../src/legacy/ui/public/styles/bootstrap/mixins.less"; `
should be?
`@import (reference) "../../../src/ui/public/styles/bootstrap/mixins.less";`

**Comment by nreese** [comment]
> There is no typo in import in time.less

No. In kibana 7.0, mixins.less has been moved under `/legacy` https://github.com/elastic/kibana/blob/master/src/legacy/ui/public/styles/bootstrap/mixins.less

**Comment by SiwyDym** [comment]
Right. But on readme there is information that on master branch works also for version 6.7 which is not true ;) I have error with this import, after fix this it's works.
Maybe add another branch for 6.7 version?

**Comment by nreese** [comment]
Looks like 6.7 does have a different import. Mind making a PR for this?

**Comment by nreese** [comment]
would you mind targeting this PR against 6.7 branch instead of master.

**Comment by SiwyDym** [comment]
Sure, i create [PR](https://github.com/nreese/kibana-time-plugin/pull/56)

**Pull request merged**
